language: java
os: linux
dist: bionic
arch: amd64
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "ultrale"
    token: 098c7f3422de05765d72563d487b0da92a6c6dcc

script:
  - mvn -DfailIfNoTests=false -Dinvoker.streamLogs=true -Dmodernizer.skip=true -Dianal.skip=true -Drat.skip=true -Dcheckstyle.skip=true -Dsass.skip=true -DfailIfNoTests=false -q -pl common/am/lib -am -Dtest=PitTest test org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=UltraLe_syncope
