language: java
os: linux
dist: bionic
arch: amd64
jdk:
  - openjdk11
# SKipping entirely the automatic install phase done by travis
install: true

# Skip automatic git pull of all submodules
git:
  submodules: false

addons:
  sonarcloud:
    organization: "ultrale"
    token: 098c7f3422de05765d72563d487b0da92a6c6dcc

script:
  - mvn clen -pl .,common/am/lib -U -T 1C -Dtest=org.apache.syncope.common.lib.*Test -Dinvoker.streamLogs=true -Dmodernizer.skip=true -Dianal.skip=true -Drat.skip=true -Dcheckstyle.skip=true -Dsass.skip=true -DfailIfNoTests=false org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=UltraLe_syncope